window.SAMPLE_DATA = {
  portfolioKpis: [
    ["Programas", "6", "Activos", "▦"],
    ["GAPs Estratégicos", "X", "Prioritarios", "⚠"],
    ["Demanda Activa", "XXX", "Iniciativas", "↗"],
    ["Evolución target", "X%", "Avance global", "◎"],
    ["Países", "X", "Alcance", "◎"],
  ],
  programs: [
    {
      id: "blue",
      name: "Blue",
      description: "Solución Agentic para cliente",
      status: "En Curso",
      functional: 50,
      systems: 50,
      architecture: 50,
      enabled: false,
      icon: "🤖",
    },
    {
      id: "orchestration",
      name: "Orchestration",
      description: "Asistencia y Orquestación",
      status: "En Curso",
      functional: 0,
      systems: 0,
      architecture: 0,
      enabled: false,
      icon: "✣",
    },
    {
      id: "futura",
      name: "Futura & Inno",
      description: "Innovación en canales digitales",
      status: "En Curso",
      functional: 0,
      systems: 0,
      architecture: 0,
      enabled: false,
      icon: "🚀",
    },
    {
      id: "smart-comms",
      name: "Smart Comms",
      description: "Comunicaciones",
      status: "En Curso",
      functional: 0,
      systems: 0,
      architecture: 0,
      enabled: false,
      icon: "💬",
    },
    {
      id: "aixbanker",
      name: "AIxBanker",
      description: "Asistente para gestores",
      status: "En Curso",
      functional: 50,
      systems: 60,
      architecture: 50,
      enabled: true,
      icon: "🧠",
    },
    {
      id: "aixrcp",
      name: "AIxRCP",
      description: "Próximos",
      status: "En Curso",
      functional: 0,
      systems: 0,
      architecture: 0,
      enabled: false,
      icon: "…",
    },
  ],
  modules: [
    {
      id: "backlog",
      title: "Backlog estratégico",
      description: "Demanda, gaps e iniciativas priorizadas.",
      route: null,
      status: "Próximamente",
    },
    {
      id: "functional",
      title: "Mapa funcional",
      description: "Dominios, capacidades y funcionalidades.",
      route: "functional",
      status: "Activo",
    },
    {
      id: "systems",
      title: "Mapa de sistemas",
      description: "Capas, componentes e inventario AS IS.",
      route: "systems",
      status: "Activo",
    },
    {
      id: "architecture",
      title: "Arquitectura de referencia",
      description: "Arquitectura target y principios.",
      route: null,
      status: "Próximamente",
    },
  ],
  roles: [
    ["PA", "Product Architect"],
    ["SA", "Solution Architect"],
    ["SeP", "Security Partner"],
    ["PTL", "Platform Tech Lead"],
    ["PBO", "Product Business Owner"],
  ],
  priorities: [
    "Panorama Buddy",
    "Competencia",
    "BBVA Assistant",
    "Streaming voz",
    "Proyecto Scout",
  ],
  functional: [
    {
      domain: "Interacción con el gestor",
      capability: "Asistente conversacional",
      features: [
        "Q&A contextual",
        "Resumen cliente",
        "Sugerencias comerciales",
      ],
    },
    {
      domain: "Bases de conocimiento",
      capability: "Conocimiento interno",
      features: ["Políticas", "Procedimientos", "Catálogo productos"],
    },
    {
      domain: "Productividad del gestor",
      capability: "Automatización tareas",
      features: ["Preparación reunión", "Minutas", "Seguimiento acciones"],
    },
    {
      domain: "Gestión comercial y ventas",
      capability: "Next best action",
      features: ["Oportunidades", "Recomendaciones", "Alertas comerciales"],
    },
    {
      domain: "Operaciones y procesos",
      capability: "Soporte operativo",
      features: ["Consulta estado", "Guía procesos", "Escalado"],
    },
    {
      domain: "Nuevo dominio",
      capability: "Capacidades futuras",
      features: ["Por definir", "Discovery", "Experimentación"],
    },
  ],
  systems: [
    {
      layer: "Canales",
      component: "Salesforce / CRM UI",
      description: "Interfaz de trabajo del gestor",
      status: "AS IS",
      country: "Global",
    },
    {
      layer: "Conversa",
      component: "Conversa Platform",
      description: "Orquestación conversacional",
      status: "AS IS",
      country: "Global",
    },
    {
      layer: "GenAI",
      component: "GenAI Framework",
      description: "Servicios de IA generativa",
      status: "AS IS",
      country: "Global",
    },
    {
      layer: "LLM Providers",
      component: "Model Providers",
      description: "Proveedores LLM corporativos",
      status: "AS IS",
      country: "Global",
    },
    {
      layer: "Fuentes de Datos",
      component: "Customer Data",
      description: "Contexto y datos de cliente",
      status: "AS IS",
      country: "Global",
    },
    {
      layer: "Otros Servicios",
      component: "Observability",
      description: "Trazabilidad, métricas y analítica",
      status: "AS IS",
      country: "Global",
    },
  ],
};
